package com.myspace.loop_reproduce;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Message implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public java.lang.Integer age;

	public Message() {
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public Message(java.lang.Integer age) {
		this.age = age;
	}

}