package com.myspace.loop_reproduce;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Test implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer fieeld;

	public Test() {
	}

	public java.lang.Integer getFieeld() {
		return this.fieeld;
	}

	public void setFieeld(java.lang.Integer fieeld) {
		this.fieeld = fieeld;
	}

	public Test(java.lang.Integer fieeld) {
		this.fieeld = fieeld;
	}

}